//
//  SJContactIntegrateLocalizedStringKeys.m
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

#import "SJContactIntegrateLocalizedStringKeys.h"

NS_ASSUME_NONNULL_BEGIN 

#if 0
(UIKIT_EXTERN\s)(SJContactIntegrateLocalizedStringKey\sconst\s)([^;]+)
$2$3 = @"$3"
#endif

SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyLongPressSpeedupContentData = @"SJContactIntegrateLocalizedStringKeyLongPressSpeedupContentData";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyNoNetwork = @"SJContactIntegrateLocalizedStringKeyNoNetwork";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyWiFiNetWork = @"SJContactIntegrateLocalizedStringKeyWiFiNetWork";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCellularNetwork = @"SJContactIntegrateLocalizedStringKeyCellularNetwork";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyReplay = @"SJContactIntegrateLocalizedStringKeyReplay";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRetry = @"SJContactIntegrateLocalizedStringKeyRetry";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyReload = @"SJContactIntegrateLocalizedStringKeyReload"; 
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyLiveBroadcast = @"SJContactIntegrateLocalizedStringKeyLiveBroadcast";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCancel = @"SJContactIntegrateLocalizedStringKeyCancel";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDone = @"SJContactIntegrateLocalizedStringKeyDone";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUnstableNetworkPrompt = @"SJContactIntegrateLocalizedStringKeyUnstableNetworkPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCellularNetworkPrompt = @"SJContactIntegrateLocalizedStringKeyCellularNetworkPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyNoNetworkPrompt = @"SJContactIntegrateLocalizedStringKeyNoNetworkPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyContentDataFailedPrompt = @"SJContactIntegrateLocalizedStringKeyContentDataFailedPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRecordsPreparingPrompt = @"SJContactIntegrateLocalizedStringKeyRecordsPreparingPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRecordsToFinishRecordingPrompt = @"SJContactIntegrateLocalizedStringKeyRecordsToFinishRecordingPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportingPrompt = @"SJContactIntegrateLocalizedStringKeyExportsExportingPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportFailedPrompt = @"SJContactIntegrateLocalizedStringKeyExportsExportFailedPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportSuccessfullyPrompt = @"SJContactIntegrateLocalizedStringKeyExportsExportSuccessfullyPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadingPrompt = @"SJContactIntegrateLocalizedStringKeyUploadsUploadingPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadFailedPrompt = @"SJContactIntegrateLocalizedStringKeyUploadsUploadFailedPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadSuccessfullyPrompt = @"SJContactIntegrateLocalizedStringKeyUploadsUploadSuccessfullyPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyScreenshotSuccessfullyPrompt = @"SJContactIntegrateLocalizedStringKeyScreenshotSuccessfullyPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumAuthDeniedPrompt = @"SJContactIntegrateLocalizedStringKeyAlbumAuthDeniedPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt = @"SJContactIntegrateLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumSavedToAlbumPrompt = @"SJContactIntegrateLocalizedStringKeyAlbumSavedToAlbumPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyOperationFailedPrompt = @"SJContactIntegrateLocalizedStringKeyOperationFailedPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchingPrompt = @"SJContactIntegrateLocalizedStringKeyDefinitionSwitchingPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt = @"SJContactIntegrateLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt";
SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchFailedPrompt = @"SJContactIntegrateLocalizedStringKeyDefinitionSwitchFailedPrompt";
NS_ASSUME_NONNULL_END
