//
//  SJContactIntegrateLocalizedStringKeys.h
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN 

typedef NSString * SJContactIntegrateLocalizedStringKey;

UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyLongPressSpeedupContentData;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyNoNetwork;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyWiFiNetWork;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCellularNetwork;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyReplay;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRetry;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyReload; 
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyLiveBroadcast;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCancel;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDone;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUnstableNetworkPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyCellularNetworkPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyNoNetworkPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyContentDataFailedPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRecordsPreparingPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyRecordsToFinishRecordingPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportingPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportFailedPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyExportsExportSuccessfullyPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadingPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadFailedPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyUploadsUploadSuccessfullyPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyScreenshotSuccessfullyPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumAuthDeniedPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyAlbumSavedToAlbumPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyOperationFailedPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchingPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt;
UIKIT_EXTERN SJContactIntegrateLocalizedStringKey const SJContactIntegrateLocalizedStringKeyDefinitionSwitchFailedPrompt;
NS_ASSUME_NONNULL_END
